### ISSUE TITLE
Lua 5.4 compatibility

### ISSUE THREAD

**Issue by amo13** [kenorb-contrib/tg#25]
After the recent update to lua 5.4 on archlinux, telegram-cli complains about missing lua 5.3 shared object:

`telegram-cli: error while loading shared libraries: liblua.so.5.3: cannot open shared object file: No such file or directory`

Of course, downgrading back to lua 5.3 solves the issue on my machine for now, but I thought I'd leave that here to let you know that this is going to happen on more machines soon...

**Comment by NaruFGT** [comment]
I believe this is an autoconf issue more than it is a telegram-cli issue. The configure.ac does not specify a lua version, it just asks for lua. 
On my machine I just tweak the autoconf variables to manually specify the lua library:
`ax_cv_lua_header_version=5.2 LUA=/usr/pkg/bin/lua5.2 LUA_LIB=/usr/pkg/lib/liblua5.2.so  LUA_INCLUDE=-I/usr/pkg/include/lua-5.2 ./configure --prefix=/somedir`
You definitely need LUA, LUA_LIB, and LUA_INCLUDE but you may also need to specify ax_cv_lua_header_version _if_ you receive a configure error about the lua header version being undefined.
As mentioned before this is the nature of `m4_include([ax_lua.m4])` and I can’t imagine a pretty maintainable workaround, maybe encourage the use of cmake? (comes with its own problems of course)

**Comment by amo13** [comment]
Thank you for the reply. Maybe someone will be able to use your ideas.
I'm closing this for now since I have ditched telegram in favor of gotify a while back.

**Comment by NaruFGT** [comment]
I’m frustrated, these aren’t “my ideas” I just explained to you that this is an autoconf problem likely specific to your distribution, and while ultimately the answer is that you should have contacted your distro’s lua maintainer, I provided a workaround. These aren’t “my ideas” in a technical sense and while the issue should be closed as not a telegram-cli issue, closing the issue because  you’re no longer interested in the software seems callous. 
So you both didn’t take the time to comprehend what I had said and you also showed no concern for following up your issue with a bug report to arch’s maintainers. 
I know autotools has a high learning curve and submitting bug reports is tedious but this half baked issue report where you write off my analysis as “ideas” just rubs me the wrong way.

**Comment by amo13** [comment]
I am sorry, I certainly did not mean to offend you with my answer. 
You are right about my lack of understanding but wrong about the cause: I *did* take to time to try and understand. What you pointed out is indeed quite technical and I am a user and no developer. I don't even know what autotools is - shame on me if that makes you feel better. Also, reporting a bug to arch maintainers runs the risk of being even less understandable for them than it is for me, at least if I report it...
I *am* thankful for you response and I am sure other telegram-cli users on arch will also be thankful for your proposed temporary workaround. That is what I wanted to say. I am just a human, didn't mean to frustrate you.

**Comment by NaruFGT** [comment]
I understand, I over-reacted. Thanks for reporting this issue.
